--- #YAML:1.0
name: DBIx-Class-FormTools
version: 0.000003
author:
  - David Jack Olrik <david@olrik.dk>
abstract: Utility module for building forms with multiple
related L<DBIx::Class> objects.
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
